spring.application.name=mockTest-1

spring.datasource.url=jdbc:mysql://localhost:3306/dmc
spring.datasource.username=mohit
spring.datasource.password=mohit
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

